### PR TITLE
added rollup target and pkg.module to get es6 module format

### PR DESCRIPTION
**Pull request by kozmanbalint**
Please consider merging this pr making it easier to use morphdom as an es6 module.

### CODE REVIEW

**Comment by AutoSponge** [comment]
👍 great idea, thanks.

**Comment by snewcomer** [comment]
@kozmanbalint would you mind bring in master and re-running rollup?

**Comment by kozmanbalint** [comment]
Thanks!

**Comment by snewcomer** [comment]
No no thank you!!

**Pull request closed without merging**
