### PR TITLE
Adding bower.json file to satisfy issue #42.

### PR DESCRIPTION
**Pull request by howardroark**
I hope this does not cause any controversy ;)  Thanks so much for obliging me!

### CODE REVIEW

**Comment by patrick-steele-idem** [comment]
Thanks for the PR. The redundancy of `bower.json` (and bower as a whole) annoys me, but oh well.

**Comment by howardroark** [comment]
You are most gracious sir!  I have registered the package `morphdom` with this git url.

It may be cool to build super simple package manager that just needed a github user/repo combo and skips having a registry altogether.  Would satisfy every exisitng bower package.

**Comment by patrick-steele-idem** [comment]
@howardroark with `npm` you can add dependencies that directly point to a Github repo:

```json
{
  "dependencies": {
    "morphdom": "patrick-steele-idem/morphdom"
  }
}
```

Of course, if those modules have dependencies they will likely be pulled from npm. I see no reason to avoid the npm registry though.

**Comment by howardroark** [comment]
Very fair!!!  I think for me it's just that I don't see js development and node development as being one in the same. Many "fullstack" developers who write js will never write node code. Not that using NPM implies that you are writing code meant for node to parse... I just think it would it's nice to have a browser package manager that is relatively agnostic.  In a larger sense `user/project` pattern frees up a lot of names for people.  I'm certainly not trying to convince you though, this is just me ;)

**Pull request merged**
