### PR TITLE
Chore: Alternate refactor to #155

### PR DESCRIPTION
**Pull request by snewcomer**
Ref #155 #153

### CODE REVIEW

**Comment by AutoSponge** [comment]
Is there a test case this solves or a benchmark this improves? Usually moving a short-circuit later causes more work which worsens performance.

**Comment by snewcomer** [comment]
This is before `morphEl` is called on first pass after `morphdom(from, to)` is called.  So a tad earlier.  This module could be reorganized a bit :)

Also not exactly planning on merging, but using it to explain some thoughts around this comment https://github.com/patrick-steele-idem/morphdom/pull/155#issuecomment-489359507 (which I was hoping to get your opinions on)

**Comment by AutoSponge** [comment]
I see. But, then I worry that there are multiple calls to `morphEl` and it's not before each of them. That sounds like a lot of duplicating code when this is really the responsibility of `morphEl`.

**Comment by snewcomer** [comment]
I think I am misunderstanding.  Based on this [comment](https://github.com/patrick-steele-idem/morphdom/pull/155#issuecomment-489359507), we only want to check `isSameNode` once.  Upon top level function execution.  After that I'm not sure we need to keep checking `isSameNode` on the root nodes over and over.  Is there a use case we want to do this?

**Comment by AutoSponge** [comment]
This PR still references a failed PR and an incorrect understanding of how hooks work. If you want to merge it, I'm not going to stop you. But I'm withdrawing as a maintainer. Please update permissions.

**Pull request merged**
