### PR TITLE
Fix bad element references

### PR DESCRIPTION
**Pull request by calebporzio**
If I'm not mistaken, morphdom is comparing the root nodes on every iteration of "morphEl()", instead of comparing the comparison nodes. I believe the mistake was made because the variable names are so similar.

I also think this line is currently useless because it's checking for "isSameNode" on two nodes that will never be the same, but that is currently being discussed in this issue: #153

### CODE REVIEW

**Comment by snewcomer** [comment]
@calebporzio Hey thanks for the PR!. So I have a few thoughts.  First, ideally we have a test case to add that proves this. On the other hand, if nothing failed, that means everything still works.  I dunno.  What do you think?

So the question is - can these nodes be referencing the same object.  This "light" check doesn't seem to hurt.  Also, see [here](https://github.com/patrick-steele-idem/morphdom/blob/master/src/morphdom.js#L425) as it seems there was an explicit purpose to test this equality.

Lastly, what do you think about just using `===` instead of isSameNode in the code you changed?

**Comment by AutoSponge** [comment]
This change makes variable naming consistent (local function reference is `*El` while closure reference is `*Node`. I don't see any test case that can prove this is needed since it's only a semantic change. I'd prefer marking it as "chore" than "fix" since it's not actually fixing anything.

**Comment by calebporzio** [comment]
@snewcomer - I believe the purpose of "isSameNode" is for vdom libraries to implement Element proxies - so changing it to "===" would be effectively the same for native DOM, but would break any vdom implementations that rely on ".isSameNode"

**Comment by snewcomer** [comment]
Ah you are right about `isSameNode`.  

Perhaps I'm missing something, but isn't this a "fix" rather than a semantic change?  In the worst case, this breaks something.  In the best case, we avoid unnecessary work.

Here is my understanding.  So `morphEl` is called multiple times after executing the program.  We are modifying the `fromNode` based on the `toNode` and move down the`toNode` tree as we go. If initially they reference the same node on **first** execution of `morphEl`, then let's not do anything and safely exit.  Post-the initial first execution of `morphEl`, if they initially referenced the same node, they will always reference the same node (unless there is a deep copy I missed somewhere) no matter what changes we make to either node...eg. `isSameNode` will return true for the rest of the program execution.  

I put up this [PR](https://github.com/patrick-steele-idem/morphdom/pull/156) for consideration as well.  I keep coming back to this code trying to learn more 😅, so would love some further discussion when you have time @calebporzio @AutoSponge

**Comment by snewcomer** [comment]
closed #156 @calebporzio Lmk if you notice any issues!  2.5.7 published!

**Pull request closed without merging**
